jwt:
  secret: 'jwt-tokens-that-should-be-changed-production'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datajabs
    password: datajabs
    username: datajabs

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
